### ISSUE TITLE
Assign reviews to PR without needing for the PR to be assigned

### ISSUE THREAD

**Issue by Nikschavan** [shufo/auto-assign-reviewer-by-assignee#6]
Currently, the PRs need to be assigned in order for the action to execute.

Can this be made optional so that the reviewers can be added to the PR without needing to assign the pull request to anyone?

**Comment by shufo** [comment]
@Nikschavan 
That's good question. This action's purpose is mainly assigned based action so currently it is not supported to assign reviewer without assigning assignee.

But you can use [auto-assign-reviewer-by-issuer](https://github.com/shufo/auto-assign-reviewer-by-issuer) to assign reviewers without needing assignee. it is issuer based action.

this configuration will assigns `foo` as reviewer to any PR

```yaml
# fallback
.*:
  - foo
```

**Comment by Nikschavan** [comment]
Thank you! `auto-assign-reviewer-by-issuer` action looks like what I am looking for, Thank you very much :)
